#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get update
sudo apt-get install haproxy=1.8.\* -y
echo "frontend web-front
         bind *:80
         default_backend web-backend
	 backend web-backend
         balance roundrobin
         server web1 52.91.146.62:80 check
         server web2 3.85.33.82:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
 sudo service haproxy start
