#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.5 -y
sudo apt-get update
sudo apt-get install haproxy=1.5.\* -y
