#!/usr/bin/env bash
# displays Good School 10 times.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 3 ]
    then
        echo "bad luck"
    elif [ $COUNTER = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    let COUNTER+=1
done
